ros-tooling/launch_ros_sandbox

- launch_ros_sandbox/actions/load_docker_nodes.py
* Support the version of Docker-py available through apt.
Signed-off-by: Zachary Michaels <zacmicha@amazon.com>
> Support version 2.5.1 of Docker-py

- README.md
Inspired by some previous work I did on https://github.com/lagadic/vision_visp
> Add build.ros2.org badges to README.md

- package.xml
Super minor change to make it consistent with the rest of the packages (see http://repo.ros2.org/status_page/ros_dashing_default.html?q=aws).
> Add author and change maintainer description in package.xml

- examples/cpu_limit_sandbox_docker.launch.py
- examples/mem_limit_sandbox_docker.launch.py
- launch_ros_sandbox/actions/load_docker_nodes.py
- test/launch_ros_sandbox/descriptions/test_docker_policy.py
- test/test_docker_policy.sh
- test/test_docker_policy_run_args.sh
- test/test_restrict_cpus.sh
This PR provides unit and E2E tests for the new `run_args` feature of `DockerPolicy`.
> DockerPolicy run_args feature unit and E2E tests

- package.xml
Fixing package.xml maintainer field to align with the other AWS packages.
> Add author and change maintainer description in package.xml (#10)

- package.xml
See https://github.com/aws-robotics/launch-ros-sandbox/pull/10
> Maintainer fix

- test/test_docker_policy_output.sh
N/A
* Add e2e test for testing stdout of nodes containerized into Docker
> Docker stdout logs e2e testing

- package.xml
Bump minor version to 0.1.0 to ensure that master has a higher minor version than dashing-devel.
> Bump minor version to 0.1.0 to ensure that master has a higher minor version than dashing-devel

- examples/bad_image.launch.py
- examples/local_image.launch.py
- launch_ros_sandbox/actions/load_docker_nodes.py
- test/dummy-dashing.Dockerfile
- test/test_docker_policy_bad_image.sh
- test/test_docker_policy_local_image.sh
* Resolves issue #24 by catching ImageNotFound exception and logging to warn
* Resolves issue #25 by continuing if Image cannot be pulled and logging to error if run still has an error.
* Log to warn when image cannot be pulled
* Log to error when image cannot be ran and exit
> Log to warn when image cannot be found and error when container cannot be run locally

- README.md
- launch_ros_sandbox.dashing.repos
- launch_ros_sandbox.repos
Help users install the package by improving the installation instructions.
This also adds two repos file, respectively for latest and dashing, in order to streamline the installation process.
Formatting changes have been made to fix all issues reported by `mdlint`.
> Improve README.md

- docs/source/conf.py
- docs/sphinx_build_symlink/setup.py
- examples/bad_image.launch.py
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
Some linter test failures. Fix them.
> Fix linter issues

- README.md
> Fix repo URL in Travis badge

- .github/workflows/test.yml
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
> Add support for OS X, and code coverage in CI

- .github/workflows/test.yml
- codecov.yml
> Fix codecov paths

- .github/workflows/lint.yml
* Update `setup-ros` to 0.0.13
* Update `action-ros-lint` to 0.0.5
> Update linting workflow

- .github/workflows/test.yml
* Update `setup-ros` to 0.0.13
* Update `action-ros-ci` to 0.0.13
* Actions are currently failing due to an Azure sync.
> Update build and test workflow

- .github/workflows/repo-activity.yaml
> Add repo activity workflow

- .github/workflows/test.yml
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
> Bump setup-ros and action-ros-ci version

- .github/workflows/lint.yml
> Run lint worflow on Docker

- .github/workflows/test.yml
> Run CI on Focal

- .github/workflows/test.yml
- .gitignore
- launch_ros_sandbox/actions/load_docker_nodes.py
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
*Issue #, if available:*. N/A
*Description of changes:* Fix `flake8` failure.
> Fix flake8 failure

- .github/workflows/lint.yml
- .github/workflows/test.yml
> Bump action-ros-ci to 0.1.0

- .github/workflows/autoapprove.yml
- .github/workflows/automerge.yml
Signed-off-by: Lucas Han <lucahan@amazon.com>
> Add automerge.yml and autoapprove.yml config files

- .github/workflows/lint.yml
- .github/workflows/test.yml
> Use latest versions of CI actions

- .github/workflows/autoapprove.yml
As per https://github.com/hmarr/auto-approve-action/issues/183
It is not currently working, for the reason described there
> Apply dependabot autoapprove fix
